service: Variabilize-Serverless-Resources-Demo

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - "Fn::GetAtt": [ DemoTestTable, Arn ]
  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:provider.stage}

custom:
  dynamoDBDeletePolicies:
    prod: Retain
    staging: Retain
    dev: Delete
    other: Delete
  dynamoDBDeletePolicy: ${self:custom.dynamoDBDeletePolicies.${self:provider.stage}, self:custom.dynamoDBDeletePolicies.other}

functions:
  get:
    handler: handler.get
    events:
      - http:
          path: /{id}/{sortKey}
          method: get
  post:
    handler: handler.post
    events:
      - http:
          path: /
          method: post

resources:
  Resources:
    DemoTestTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: ${self:custom.dynamoDBDeletePolicy}
      Properties:
        AttributeDefinitions:
          - AttributeName: hashKey
            AttributeType: S
          - AttributeName: sortKey
            AttributeType: S
        KeySchema:
          - AttributeName: hashKey
            KeyType: HASH
          - AttributeName: sortKey
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: Demo-${self:provider.stage}-Table